---

logging:
    version: 1
    disable_existing_loggers: False

    formatters:
        simple:
            format: "%(asctime)s %(levelname)s - %(name)s - %(module)s - %(funcName)s --> %(message)s"
            datefmt: "%Y-%m-%d %H:%M:%S"

    handlers:
        console:
            class: logging.StreamHandler
            level: INFO
            formatter: simple
            stream: ext://sys.stdout
        info_file_handler:
            class: logging.FileHandler
            level: INFO
            formatter: simple
            filename: ../../logs/cartier.log
            encoding: utf8
        error_file_handler:
            class: logging.FileHandler
            level: ERROR
            formatter: simple
            filename: ../../logs/errors.log
            encoding: utf8

    loggers:
        my_module:
            level: ERROR
            handlers: [console]
            propagate: false
        '':  # 默认的logger
            level: INFO
            handlers: [console, info_file_handler, error_file_handler]

...